import type { Customer } from "../../interfaces";

export const SEED_CUSTOMERS: Omit<Customer, "id" | "slug" | "created_at" | "updated_at">[] = [
	{
		code: "CUST001",
		name: "Mercadona S.A.",
		type: "Cliente",
		email: "pedidos@mercadona.es",
		phone: "+34 900 123 456",
		status: "Activo",
	},
	{
		code: "CUST002",
		name: "Carrefour España",
		type: "Cliente",
		email: "compras@carrefour.es",
		phone: "+34 900 234 567",
		status: "Activo",
	},
	{
		code: "CUST003",
		name: "El Corte Inglés",
		type: "Cliente",
		email: "logistica@elcorteingles.es",
		phone: "+34 900 345 678",
		status: "Activo",
	},
	{
		code: "SUPP001",
		name: "Distribuciones García SL",
		type: "Proveedor",
		email: "ventas@distgarcia.com",
		phone: "+34 963 123 456",
		status: "Activo",
	},
	{
		code: "SUPP002",
		name: "Logística Martínez",
		type: "Proveedor",
		email: "info@logmartinez.es",
		phone: "+34 932 234 567",
		status: "Activo",
	},
	{
		code: "CLI010",
		name: "Repsol Química S.A.",
		type: "Cliente",
		email: "compras.quimica@repsol.com",
		phone: "+34 910 100 100",
		status: "Activo",
	},
	{
		code: "CLI011",
		name: "Dow Chemical Ibérica S.L.",
		type: "Cliente",
		email: "compras.iberia@dow.com",
		phone: "+34 977 559 000",
		status: "Activo",
	},
	{
		code: "CLI012",
		name: "BASF Española S.L.",
		type: "Cliente",
		email: "pedidos.es@basf.com",
		phone: "+34 934 969 000",
		status: "Activo",
	},
	{
		code: "CLI013",
		name: "Cepsa Química S.A.",
		type: "Cliente",
		email: "suministros@cepsa.com",
		phone: "+34 913 377 000",
		status: "Activo",
	},
	{
		code: "CLI014",
		name: "MASA Mantenimiento Industrial",
		type: "Cliente",
		email: "compras@masa.es",
		phone: "+34 977 000 100",
		status: "Activo",
	},
	{
		code: "CLI015",
		name: "Ercros S.A.",
		type: "Cliente",
		email: "compras@ercros.es",
		phone: "+34 934 393 000",
		status: "Activo",
	},
	{
		code: "CLI016",
		name: "Iqoxe S.L.",
		type: "Cliente",
		email: "mantenimiento@iqoxe.com",
		phone: "+34 977 000 200",
		status: "Activo",
	},
	{
		code: "CLI017",
		name: "Messer Ibérica de Gases S.A.",
		type: "Cliente",
		email: "pedidos@messer.es",
		phone: "+34 977 000 300",
		status: "Activo",
	},
	{
		code: "CLI018",
		name: "Air Liquide España S.A.",
		type: "Cliente",
		email: "suministros@airliquide.com",
		phone: "+34 915 300 900",
		status: "Activo",
	},
	{
		code: "CLI019",
		name: "Enagás S.A.",
		type: "Cliente",
		email: "compras@enagas.es",
		phone: "+34 910 000 400",
		status: "Activo",
	},
	{
		code: "CLI020",
		name: "Petronor S.A.",
		type: "Cliente",
		email: "almacen@petronor.es",
		phone: "+34 946 000 500",
		status: "Activo",
	},
	{
		code: "CLI021",
		name: "CLH Compañía Logística de Hidrocarburos",
		type: "Cliente",
		email: "compras@clh.es",
		phone: "+34 910 000 600",
		status: "Pendiente",
	},
	{
		code: "SUPP010",
		name: "Novus (Flexitallic)",
		type: "Proveedor",
		email: "ventas@novus.es",
		phone: "+34 910 000 700",
		status: "Activo",
	},
	{
		code: "SUPP011",
		name: "Klinger Ibérica S.A.",
		type: "Proveedor",
		email: "pedidos@klinger.es",
		phone: "+34 930 000 800",
		status: "Activo",
	},
	{
		code: "SUPP012",
		name: "Garlock España S.L.",
		type: "Proveedor",
		email: "ventas@garlock.es",
		phone: "+34 930 000 900",
		status: "Activo",
	},
	{
		code: "SUPP013",
		name: "Lamons Ibérica S.L.",
		type: "Proveedor",
		email: "info@lamons.es",
		phone: "+34 930 001 000",
		status: "Activo",
	},
	{
		code: "SUPP014",
		name: "Aceros Inox Tarragona",
		type: "Proveedor",
		email: "compras@acerosinox.es",
		phone: "+34 977 100 200",
		status: "Activo",
	},
	{
		code: "TRAN001",
		name: "Transportes Logísticos Riu Clar S.L.",
		type: "Transportista",
		email: "trafico@transriuclar.es",
		phone: "+34 977 000 900",
		status: "Activo",
	},
];
