import type { Order } from "../../interfaces";

export const SEED_ORDERS: Omit<Order, "id" | "slug" | "created_at" | "updated_at">[] = [
	{
		order_number: "PED-2026-001",
		customer_name: "Mercadona S.A.",
		status: "Pendiente",
		priority: "high",
		total_items: 3,
		total_value: 1850.5,
	},
	{
		order_number: "PED-2026-002",
		customer_name: "Carrefour España",
		status: "Picking",
		priority: "normal",
		total_items: 5,
		total_value: 3250,
	},
	{
		order_number: "PED-2026-003",
		customer_name: "El Corte Inglés",
		status: "Pendiente",
		priority: "normal",
		total_items: 2,
		total_value: 890,
	},
	{
		order_number: "PED-2026-004",
		customer_name: "Mercadona S.A.",
		status: "Packing",
		priority: "high",
		total_items: 4,
		total_value: 2100,
	},
	{
		order_number: "PED-2026-005",
		customer_name: "Carrefour España",
		status: "Despachado",
		priority: "normal",
		total_items: 6,
		total_value: 4500,
	},
	{
		order_number: "PED-2026-006",
		customer_name: "El Corte Inglés",
		status: "Pendiente",
		priority: "high",
		total_items: 8,
		total_value: 6750,
	},
	{
		order_number: "PED-2026-007",
		customer_name: "Repsol Química S.A.",
		status: "Pendiente",
		priority: "high",
		total_items: 4,
		total_value: 3240,
	},
	{
		order_number: "PED-2026-008",
		customer_name: "Dow Chemical Ibérica S.L.",
		status: "Picking",
		priority: "normal",
		total_items: 6,
		total_value: 4180.5,
	},
	{
		order_number: "PED-2026-009",
		customer_name: "BASF Española S.L.",
		status: "Packing",
		priority: "normal",
		total_items: 3,
		total_value: 1560,
	},
	{
		order_number: "PED-2026-010",
		customer_name: "Cepsa Química S.A.",
		status: "Despachado",
		priority: "high",
		total_items: 8,
		total_value: 6240.75,
	},
	{
		order_number: "PED-2026-011",
		customer_name: "MASA Mantenimiento Industrial",
		status: "Pendiente",
		priority: "normal",
		total_items: 2,
		total_value: 740,
	},
	{
		order_number: "PED-2026-012",
		customer_name: "Ercros S.A.",
		status: "Despachado",
		priority: "normal",
		total_items: 5,
		total_value: 2890,
	},
	{
		order_number: "PED-2026-013",
		customer_name: "Iqoxe S.L.",
		status: "Picking",
		priority: "normal",
		total_items: 4,
		total_value: 1980,
	},
	{
		order_number: "PED-2026-014",
		customer_name: "Messer Ibérica de Gases S.A.",
		status: "Completado",
		priority: "normal",
		total_items: 3,
		total_value: 1250,
	},
	{
		order_number: "PED-2026-015",
		customer_name: "Air Liquide España S.A.",
		status: "Pendiente",
		priority: "urgent",
		total_items: 10,
		total_value: 7480,
	},
	{
		order_number: "PED-2026-016",
		customer_name: "Enagás S.A.",
		status: "Packing",
		priority: "high",
		total_items: 7,
		total_value: 5120,
	},
	{
		order_number: "PED-2026-017",
		customer_name: "Petronor S.A.",
		status: "Despachado",
		priority: "normal",
		total_items: 9,
		total_value: 6890,
	},
	{
		order_number: "PED-2026-018",
		customer_name: "CLH Compañía Logística de Hidrocarburos",
		status: "Pendiente",
		priority: "normal",
		total_items: 4,
		total_value: 2310,
	},
	{
		order_number: "PED-2026-019",
		customer_name: "Repsol Química S.A.",
		status: "Completado",
		priority: "high",
		total_items: 6,
		total_value: 4390,
	},
	{
		order_number: "PED-2026-020",
		customer_name: "Dow Chemical Ibérica S.L.",
		status: "Pendiente",
		priority: "normal",
		total_items: 5,
		total_value: 3620,
	},
	{
		order_number: "PED-2026-021",
		customer_name: "BASF Española S.L.",
		status: "Picking",
		priority: "normal",
		total_items: 3,
		total_value: 1420,
	},
	{
		order_number: "PED-2026-022",
		customer_name: "Cepsa Química S.A.",
		status: "Packing",
		priority: "high",
		total_items: 8,
		total_value: 5980,
	},
	{
		order_number: "PED-2026-023",
		customer_name: "MASA Mantenimiento Industrial",
		status: "Despachado",
		priority: "normal",
		total_items: 2,
		total_value: 680,
	},
	{
		order_number: "PED-2026-024",
		customer_name: "Ercros S.A.",
		status: "Pendiente",
		priority: "low",
		total_items: 3,
		total_value: 1150,
	},
	{
		order_number: "PED-2026-025",
		customer_name: "Iqoxe S.L.",
		status: "Completado",
		priority: "normal",
		total_items: 4,
		total_value: 2070,
	},
	{
		order_number: "PED-2026-026",
		customer_name: "Air Liquide España S.A.",
		status: "Picking",
		priority: "urgent",
		total_items: 12,
		total_value: 8930,
	},
	{
		order_number: "PED-2026-027",
		customer_name: "Enagás S.A.",
		status: "Pendiente",
		priority: "high",
		total_items: 6,
		total_value: 4610,
	},
	{
		order_number: "PED-2026-028",
		customer_name: "Petronor S.A.",
		status: "Packing",
		priority: "normal",
		total_items: 7,
		total_value: 5240,
	},
	{
		order_number: "PED-2026-029",
		customer_name: "Mercadona S.A.",
		status: "Despachado",
		priority: "normal",
		total_items: 6,
		total_value: 4500,
	},
	{
		order_number: "PED-2026-030",
		customer_name: "Carrefour España",
		status: "Completado",
		priority: "normal",
		total_items: 5,
		total_value: 3250,
	},
	{
		order_number: "REC-2026-001",
		customer_name: "Distribuciones García SL",
		status: "Pendiente",
		priority: "normal",
		total_items: 12,
		total_value: 1450,
	},
	{
		order_number: "REC-2026-002",
		customer_name: "Logística Martínez",
		status: "Completado",
		priority: "normal",
		total_items: 24,
		total_value: 3800,
	},
	{
		order_number: "REC-2026-003",
		customer_name: "Novus (Flexitallic)",
		status: "Completado",
		priority: "normal",
		total_items: 18,
		total_value: 2450,
	},
	{
		order_number: "REC-2026-004",
		customer_name: "Klinger Ibérica S.A.",
		status: "Pendiente",
		priority: "normal",
		total_items: 12,
		total_value: 1620,
	},
	{
		order_number: "REC-2026-005",
		customer_name: "Garlock España S.L.",
		status: "Control de Calidad",
		priority: "normal",
		total_items: 8,
		total_value: 1180,
	},
	{
		order_number: "REC-2026-006",
		customer_name: "Lamons Ibérica S.L.",
		status: "Pendiente",
		priority: "high",
		total_items: 15,
		total_value: 2210,
	},
	{
		order_number: "REC-2026-007",
		customer_name: "Aceros Inox Tarragona",
		status: "Completado",
		priority: "normal",
		total_items: 22,
		total_value: 3840,
	},
	{
		order_number: "REC-2026-008",
		customer_name: "Distribuciones García SL",
		status: "Pendiente",
		priority: "normal",
		total_items: 10,
		total_value: 1350,
	},
	{
		order_number: "REC-2026-009",
		customer_name: "Logística Martínez",
		status: "Completado",
		priority: "normal",
		total_items: 24,
		total_value: 3800,
	},
	{
		order_number: "REC-2026-010",
		customer_name: "Novus (Flexitallic)",
		status: "Control de Calidad",
		priority: "normal",
		total_items: 20,
		total_value: 2790,
	},
	{
		order_number: "REC-2026-011",
		customer_name: "Klinger Ibérica S.A.",
		status: "Pendiente",
		priority: "normal",
		total_items: 14,
		total_value: 1930,
	},
	{
		order_number: "REC-2026-012",
		customer_name: "Garlock España S.L.",
		status: "Completado",
		priority: "normal",
		total_items: 9,
		total_value: 1320,
	},
	{
		order_number: "REC-2026-013",
		customer_name: "Lamons Ibérica S.L.",
		status: "Pendiente",
		priority: "normal",
		total_items: 16,
		total_value: 2380,
	},
	{
		order_number: "REC-2026-014",
		customer_name: "Aceros Inox Tarragona",
		status: "Control de Calidad",
		priority: "normal",
		total_items: 26,
		total_value: 4120,
	},
];
