import type { PickingTask } from "../../interfaces";

export const SEED_PICKING: Omit<PickingTask, "id" | "slug" | "created_at" | "updated_at">[] = [
	{
		task_number: "PICK-001",
		order_number: "PED-2026-001",
		assigned_to: "Carlos Ruiz",
		zone: "A",
		status: "Pendiente",
		total_items: 3,
		picked_items: 0,
	},
	{
		task_number: "PICK-002",
		order_number: "PED-2026-002",
		assigned_to: "María López",
		zone: "B",
		status: "En Proceso",
		total_items: 5,
		picked_items: 2,
	},
	{
		task_number: "PICK-003",
		order_number: "PED-2026-003",
		assigned_to: "Carlos Ruiz",
		zone: "C",
		status: "Pendiente",
		total_items: 2,
		picked_items: 0,
	},
	{
		task_number: "PICK-004",
		order_number: "PED-2026-004",
		assigned_to: "Pedro Sánchez",
		zone: "A",
		status: "En Proceso",
		total_items: 4,
		picked_items: 1,
	},
	{
		task_number: "PICK-005",
		order_number: "PED-2026-005",
		assigned_to: "Lucía Fernández",
		zone: "B",
		status: "Completado",
		total_items: 6,
		picked_items: 6,
	},
	{
		task_number: "PICK-006",
		order_number: "PED-2026-006",
		assigned_to: "Juan Torres",
		zone: "C",
		status: "Pendiente",
		total_items: 8,
		picked_items: 0,
	},
	{
		task_number: "PICK-007",
		order_number: "PED-2026-007",
		assigned_to: "David Moreno",
		zone: "A",
		status: "En Proceso",
		total_items: 4,
		picked_items: 2,
	},
	{
		task_number: "PICK-008",
		order_number: "PED-2026-008",
		assigned_to: "Marta Vidal",
		zone: "B",
		status: "Pendiente",
		total_items: 6,
		picked_items: 0,
	},
	{
		task_number: "PICK-009",
		order_number: "PED-2026-009",
		assigned_to: "Javier Ortega",
		zone: "C",
		status: "Completado",
		total_items: 3,
		picked_items: 3,
	},
	{
		task_number: "PICK-010",
		order_number: "PED-2026-010",
		assigned_to: "Pedro Sánchez",
		zone: "A",
		status: "En Proceso",
		total_items: 8,
		picked_items: 5,
	},
	{
		task_number: "PICK-011",
		order_number: "PED-2026-011",
		assigned_to: "Juan Torres",
		zone: "B",
		status: "Pendiente",
		total_items: 2,
		picked_items: 0,
	},
	{
		task_number: "PICK-012",
		order_number: "PED-2026-012",
		assigned_to: "Lucía Fernández",
		zone: "C",
		status: "Completado",
		total_items: 5,
		picked_items: 5,
	},
	{
		task_number: "PICK-013",
		order_number: "PED-2026-013",
		assigned_to: "David Moreno",
		zone: "A",
		status: "Pendiente",
		total_items: 4,
		picked_items: 0,
	},
	{
		task_number: "PICK-014",
		order_number: "PED-2026-014",
		assigned_to: "Marta Vidal",
		zone: "B",
		status: "Completado",
		total_items: 3,
		picked_items: 3,
	},
	{
		task_number: "PICK-015",
		order_number: "PED-2026-015",
		assigned_to: "Javier Ortega",
		zone: "C",
		status: "En Proceso",
		total_items: 10,
		picked_items: 4,
	},
	{
		task_number: "PICK-016",
		order_number: "PED-2026-016",
		assigned_to: "Pedro Sánchez",
		zone: "A",
		status: "En Proceso",
		total_items: 7,
		picked_items: 6,
	},
	{
		task_number: "PICK-017",
		order_number: "PED-2026-017",
		assigned_to: "Juan Torres",
		zone: "B",
		status: "Completado",
		total_items: 9,
		picked_items: 9,
	},
	{
		task_number: "PICK-018",
		order_number: "PED-2026-018",
		assigned_to: "Lucía Fernández",
		zone: "C",
		status: "Pendiente",
		total_items: 4,
		picked_items: 0,
	},
	{
		task_number: "PICK-019",
		order_number: "PED-2026-019",
		assigned_to: "David Moreno",
		zone: "A",
		status: "Completado",
		total_items: 6,
		picked_items: 6,
	},
	{
		task_number: "PICK-020",
		order_number: "PED-2026-020",
		assigned_to: "Marta Vidal",
		zone: "B",
		status: "En Proceso",
		total_items: 5,
		picked_items: 2,
	},
	{
		task_number: "PICK-021",
		order_number: "PED-2026-021",
		assigned_to: "Javier Ortega",
		zone: "C",
		status: "Pendiente",
		total_items: 3,
		picked_items: 0,
	},
	{
		task_number: "PICK-022",
		order_number: "PED-2026-022",
		assigned_to: "Pedro Sánchez",
		zone: "A",
		status: "En Proceso",
		total_items: 8,
		picked_items: 3,
	},
	{
		task_number: "PICK-023",
		order_number: "PED-2026-023",
		assigned_to: "Juan Torres",
		zone: "B",
		status: "Completado",
		total_items: 2,
		picked_items: 2,
	},
	{
		task_number: "PICK-024",
		order_number: "PED-2026-024",
		assigned_to: "Lucía Fernández",
		zone: "C",
		status: "Pendiente",
		total_items: 3,
		picked_items: 0,
	},
	{
		task_number: "PICK-025",
		order_number: "PED-2026-025",
		assigned_to: "David Moreno",
		zone: "A",
		status: "En Proceso",
		total_items: 4,
		picked_items: 1,
	},
	{
		task_number: "PICK-026",
		order_number: "PED-2026-026",
		assigned_to: "Marta Vidal",
		zone: "B",
		status: "Pendiente",
		total_items: 12,
		picked_items: 0,
	},
	{
		task_number: "PICK-027",
		order_number: "PED-2026-027",
		assigned_to: "Javier Ortega",
		zone: "C",
		status: "En Proceso",
		total_items: 6,
		picked_items: 2,
	},
	{
		task_number: "PICK-028",
		order_number: "PED-2026-028",
		assigned_to: "Pedro Sánchez",
		zone: "A",
		status: "Completado",
		total_items: 7,
		picked_items: 7,
	},
	{
		task_number: "PICK-029",
		order_number: "PED-2026-029",
		assigned_to: "Juan Torres",
		zone: "B",
		status: "Completado",
		total_items: 6,
		picked_items: 6,
	},
	{
		task_number: "PICK-030",
		order_number: "PED-2026-030",
		assigned_to: "Lucía Fernández",
		zone: "C",
		status: "Completado",
		total_items: 5,
		picked_items: 5,
	},
];
